### ISSUE TITLE
Polkadot bridges RFP  - come build bridges with us!

### ISSUE THREAD

**Issue by dfishb** [w3f/General-Grants-Program#155]
The Web3 Foundation is looking to attract teams interested in designing and implementing bridges!

Bridges are specialized parachains that allow communication to external blockchain networks such as Bitcoin or Ethereum, that are not secured by Polkadot’s relay chain. In order to achieve the broadest notion of interoperability, it’s crucial that bridges are constructed for as many different existing blockchain networks as possible.

For more information and for details on how to apply, please see the following document:

[Polkadot Bridges RFP](https://docs.google.com/document/d/1yMpiSAAvGeRebLlzl5fmcq_LloIViperTw4UUEuQYzM/edit)

The Web3 Foundation would like to support bridge development with all major blockchain networks. However, the highest priorities for us at the moment are bridges to Ethereum and Zcash.

Please also check our or [riot channel](https://riot.im/app/#/room/#bridges:web3.foundation) for bridges. 

***UPDATE***
We have already selected a team to develop the specification and PoC for a Bitcoin bridge and are not currently interested in further applications for this.

**Comment by SotaWatanabe** [comment]
Hello @dfishb. I am Sota Watanabe, CEO at Stake Technologies and we are making Plasm, a plasma parachain based on Substrate. 
https://github.com/stakedtechnologies/Plasm

Since we are making a Plasma chain, we are very very interested in making a plasma bridge between Polkadot and X (As a first step, we are focusing on Ethereum).
https://medium.com/staked-technologies/4-reasons-why-we-need-plasma-in-the-polkadot-ecosystem-ffad28593e7e

And we have been thinking about a bridge structure. Now we just have a Japanese draft. I am translating it into English. Once we finish the translation, please let me share with you.

Thanks!

**Comment by prastut** [comment]
@dfishb my team was interested to build a bridge for ZCash but it seems you have already funded one grant application: https://github.com/LayerXcom/zero-chain. 

Can you tell me what it is that you are looking for when you mention ZCash as a high priority bridge?

**Comment by lsaether** [comment]
@prastut Zerochain is a standalone implementation of a privacy modules on Substrate. A bridge to ZCash would allow for sending ZEC back and forth between ZCash chain and Polkadot.

**Comment by prastut** [comment]
@lsaether ahh got it.

**Comment by EdwardAThomson** [comment]
> Can you tell me what it is that you are looking for when you mention ZCash as a high priority bridge?

If you can also figure out how to do shielded to shielded bridging then you would have solved a tough problem! Generally, bridge operators have capital at stake that's slashed for bad behaviour. Naturally, you need to know how the value of the tokens in the bridge in order to know whether there is enough capital at risk, but it seems that is tricky to do for shielded Zcash transactions.

**Comment by brenzi** [comment]
We just re-supplied our speculative PR #140 as a targeted one for this RFP. Looking forward to feedback.

**Comment by dfishb** [comment]
Hi everyone - we will be closing this round of applications and starting to make initial decisions on funding as of September 13th.

We will still be accepting applications after this date, but the scope of projects we fund will depend on decisions made in the first round.

**Comment by soc1c** [comment]
#111

**Comment by gcsfred** [comment]
If any team needs a general collaborator for specific tasks, I'm interested in helping out. Especially with developing a bridge to ZCash and QA.

**Comment by domob1812** [comment]
We (@xaya) are interested in building a Bitcoin bridge.  We've already been in discussion with you guys anyway, but posting here for others to see can't hurt.  We are finalising our extended proposal document at the moment.

**Comment by usetech-llc** [comment]
Hi guys! EOS bridge proposal coming your way from us!

**Comment by ccdex-top** [comment]
We are building a cross-chain bridge for Polkadot.  The algorithm based on MPC that can support distributed generation of EDDSA/ED25519 signature. @gcsfred

**Comment by krzysztof-jelski** [comment]
Just submitted an implementation-only proposal. We'd be happy to pair with some specification team!

**Comment by musnit** [comment]
Just submitted a proposal too!

**Comment by fanyang1988** [comment]
#180 A bridge to EOS and chain based on EOSIO
