### ISSUE TITLE
Meetup - Polkadot - Kuala Lumpur, Malaysia

### ISSUE THREAD

**Issue by ankurdaharwal** [w3f/General-Grants-Program#23]
Hi,

I would be delighted to organize a meetup of Web3 foundation for KL region.

I'm currently researching on Scalability and Polkadot, Parity Substrate.

I'm sure we'll have lots of interest in the Polkadot innovation. A lot of Open Source Developers will be interested to participate and be involved in the Web3 Ecosystem.

Best Regards,
Ankur Daharwal
ankur.daharwal@gmail.com

**Comment by EdwardAThomson** [comment]
Hey Ankur

Thanks for reaching out. We appreciate the enthusiasm and the desire to help organise meetups in your region.

As I pointed out to Ankit in the [Bangalore meetup issue](https://github.com/w3f/Web3-collaboration/issues/22), we're still sorting out the process of how we want to manage and engage with the community in order to get the most out of meetups globally. We can get you some presentation material for the meetups, so bare with us as we get this figured out!

I've added the tags to this issue and also fixed the title to include the country name.

I would also suggest that you fill out our meetup collaboration form: [link](https://docs.google.com/forms/d/e/1FAIpQLSe-hbgzMHkwYLCy9-0NLmnpIJdD-nwq_vqNwba9JiiKFmZmZg/viewform). It helps to make it easier for us to keep in touch, plus figure out the sort of events you would like to organise. :-)

Cheers
Edward
