### ISSUE TITLE
Clarify abstract to grants table. What is a breach of terms

### ISSUE THREAD

**Issue by polkastar** [w3f/General-Grants-Program#452]
Hi I am interested in some of the projects listed here. What does breach of terms mean and can that include projects that decided to stop doing their grant? Are all terminations because of bad reasons? 

"Furthermore, the page lists terminations which happened due to a breach of the terms of the grants programs. Additionally, teams might have decided to stop working on the grant—though not necessarily on the project itself—for various reasons, which is not reflected on this sheet."

Does the second sentence apply to the first? This isn't clear to me. I ask some teams and they say not only for bad reason. It need to be clearer

**Comment by Noc2** [comment]
Thanks for your interest in the grants accepted list. Currently the list **doesn’t list teams as terminated that simply decided to stop working on a project**. We only list terminations that “happened due to a breach of the terms of the grants programs”. Most of the time the reason for the termination was that these teams used code without proper attribution. 

If you want to learn more about the evaluations, I recommend to take a look at the [evaluations folder](https://github.com/w3f/Grant-Milestone-Delivery/tree/master/evaluations) as well as the corresponding PRs to the delivery repo. However this includes only open grants, since it’s only a requirement for them to submit the delivery publicly.  

Let me know if you have any other questions.

**Comment by polkastar** [comment]
I wrote to one i was interested in because i know some of the developer and he said he was not terminated because of this but because they didnt have a monetization model and ran out funds to complete milestones on time. "Most of the time the reason for the termination was that these teams used code without proper attribution." make their developers look worse than what happened. This should be clarified I can ask him to respond

**Comment by alxs** [comment]
@polkastar in that case the grant shouldn't be listed as terminated. It's possible that a team that was simply delayed, or stopped working on the grant voluntarily, was marked as terminated by mistake. If the team wants to answer here we'll make sure to look into the matter and amend the list if needed.

**Comment by polkastar** [comment]
Ok i ask him. He said it was terminated but because of late and no longer needed milestones. Does this count or not?

**Comment by Noc2** [comment]
It would make it a lot easier if you could tell us which team you are referring to and we will look into it. Again, the list officially only lists terminations that happened due to a breach of the terms of the grants programs. Let us know in case you think a team is listed  here as terminated for the wrong reason.

**Comment by Noc2** [comment]
In case you were referring to the speckle os grant, I just updated just updated the list: https://github.com/w3f/Open-Grants-Program/blob/deprecate-general-grants/src/accepted_grant_applications.md This was indeed a mistake from us. I’m sorry for this and thanks a lot for bringing this to our attention. I’m closing the issue. Let me know in case you were referring to a different grant.
