### ISSUE TITLE
Meetup - Polkadot - Sofia, Bulgaria

### ISSUE THREAD

**Issue by mradkov** [w3f/General-Grants-Program#47]
My name is Milen and I'm the founder of [hack - Blockchain Development and Consulting](https://hack.bg), a Bulgarian based blockchain development agency. We provide development of decentralized applications, smart contracts, security audits and consultations. We are mainly working with Ethereum, but we have experience and projects over Hyperledger and other blockchain/ DLT infrastructure as well. Besides our work as developers, we are also organizing and hosting regular meetups for our local community. Our meetup is named [Blockchain Developers Meetup Bulgaria](https://meetup.com/Blockchain-Developers-Meetup-Bulgaria) and we are doing workshops, webinars, talks and discussions regarding interesting blockchain development topics. We tend to keep it more development oriented and that's why our community is consisted of very enthusiastic and skilled developers.

- **What is the plan**: To organize a Polkadot meetup in Sofia, Bulgaria. The initial meetup is planned for the end of November, where we will introduce Polkadot to our community, and talk about the basics. Furthermore we are planning to explore deeply Polkadot and continue making other meetups/events about more sophisticated use cases of Polkadot. We would greatly appreciate if some from Polkadot can join some of our events, give a talk/presentation and meet our community.
Our meetup group is already consisted of 100+ blockchain developers interested and attending at our events. We are doing all the marketing and organization, as well as providing all the necessary details to our community.

- **Number of people on your team**: At our Blockchain Developers Meetup there are usually between 30 and 50 people attending regularly. We also have a gorgeous camera girl that is capturing the best and awesome moments of every event we organize. We are recording and streaming our events.

- **Do you need help from W3F**: A team member to do a presentation on Polkadot would be necessary. We are self-funded and are paying for our expenses (venue, snacks & etc..) on our own, but it is quite costly and we would appreciate any kind of support/funding. Our community loves swag, so if we could get some t-shirts and stickers, that would be awesome!

- **Do you need help from the community**: Attendance would be greatly appreciated. As would some help to promote the event.

**Comment by EdwardAThomson** [comment]
Hey @mradkov thanks for the note of interest. 

We can most likely get someone to come and visit Sofia. It sounds like you have a solid community there. As you have hopefully seen from other cities, we've already started to send people from W3F / Parity to present on Substrate and Polkadot. These talks have been mostly at a a high level. This is great for helping us spread the word, but we know that devs are really eager to have a workshop or a hackathon. Fortunately, we've working on that but it may be sometime into 2019 once we are ready.

The high level content could be presented by a knowledgeable community member (e.g. someone in Sofia), albeit they may not know the answer to all questions thrown at them.

Covering some / most / all event costs can be possible too. Help to promote is easy enough, since we can tweet it out and post to Reddit (plus Riot / Telegram etc).

We're also updating our meetup process to make it easier for the community to participate. We have someone new who just joined our team, called John, and will be dedicated to helping us with events.

**Comment by mradkov** [comment]
Thank you @EdwardAThomson !

Let's keep in touch and make the best out of it. I'm also in your riot channel.
